apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sysdig-vm-reports-pvc
spec:
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 50Gi 
  storageClassName: longhorn 