# kubectl create job --from=cronjob/sysdig-vm-import sysdig-vm-import-manual
apiVersion: batch/v1
kind: CronJob
metadata:
  name: sysdig-vm-import-job
  namespace: sysdig-vm-dashboard
spec:
  timeZone: 'Australia/Sydney' 
  schedule: "30 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            runAsUser: 1000
            fsGroup: 1000
          containers:
          - name: sysdig-vm-import-job
            image: ghcr.io/andrewd-sysdig/sysdig-vm-dashboard:latest # You may want to update this to pin it to a version
            imagePullPolicy: IfNotPresent
            resources:
              requests:
                memory: "512Mi" 
                cpu: "1000m"  # Single threaded python so no need for more than 1CPU
              limits:
                memory: "3000Mi" 
                cpu: "1000m"
            env:
            - name: LOG_LEVEL
              value: "INFO"
            - name: TZ
              value: "Australia/Sydney"
            - name: IMPORT_BATCH_SIZE
              value: "500000" # How many records to import at a a time from CSV. 500k should use less than 1GB memory. Lower will be slower.
            - name: VULN_NOT_SEEN_CLOSE
              value: "1"
            - name: REPORT_DOWNLOADS
              value: "sysdig_reports/to_process" # Where the .csv.gz reports will be downlaoded to before processing - This should be a PVC
            - name: REPORT_ARCHIVE_DIR
              value: "sysdig_reports/archive" # Where the .csv.gz reports are moved after processing - This should be a PVC
            - name: REPORT_SCHEDULE_ID
              value: "2H3Sl0FjEkIocMkVAIfq6CFRSD6" # Report Schedule ID comes from Sysdig UI, click your "All Vulnerabilities" report and grab the Schedule ID from the URL bar
            - name: SYSDIG_SECURE_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: sysdig-secure-api-token
                  key: SYSDIG_SECURE_API_TOKEN
            - name: SYSDIG_REGION_URL
              value: "https://app.au1.sysdig.com" # Your Sysdig Region URL
            - name: ALL_VULNS_TABLE_NAME
              value: "sysdig_vulns" # Name of the table to use in clickhouse to store the vulnerability data (You shouldn't need to change this)
            - name: VULN_SEVERITY_TO_KEEP
              value: "High,Critical" # Which severities to keep in the DB from the CSV
            - name: CLICKHOUSE_HOSTNAME
              value: "clickhouse" # Only need to change if you change the cluster IP svc name
            - name: CLICKHOUSE_USER
              value: "sysdig_vm_user" # Username for Clickhouse DB (You shouldn't need to change this)
            - name: CLICKHOUSE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: clickhouse-password
                  key: CLICKHOUSE_PASSWORD
            #command: ["sleep", "infinity"]
            volumeMounts:
            - name: data
              mountPath: /sysdig_reports
          volumes:
          - name: data
            persistentVolumeClaim:
              claimName: sysdig-vm-reports-pvc
          restartPolicy: OnFailure