# kubectl create job --from=cronjob/sysdig-vm-import sysdig-vm-import-manual
apiVersion: batch/v1
kind: CronJob
metadata:
  name: sysdig-vm-import-job
  namespace: sysdig-vm-dashboard
spec:
  timeZone: 'Australia/Sydney' 
  schedule: "30 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: sysdig-vm-import-job
            image: ghcr.io/andrewd-sysdig/sysdig-vm-dashboard:latest # You may want to update this to pin it to a version
            imagePullPolicy: IfNotPresent
            resources:
              requests:
                memory: "2048Mi" # Memory used by this job seems to peak at twice the size of the uncompressed CSV file
                cpu: "1000m"
            env:
            - name: BATCH_SIZE
              value: "500000" # You shouldn't need to change this
            - name: UPDATE_BATCH_SIZE
              value: "5000" # You shouldn't need to change this
            - name: VULN_NOT_SEEN_CLOSE
              value: "1" # Number of days to wait before closing a vulnerability that hasn't been seen in a report
            - name: REPORT_DOWNLOADS
              value: "sysdig_reports/to_process" # Where the .csv.gz reports will be downlaoded to before processing - This should be a PVC
            - name: REPORT_ARCHIVE_DIR
              value: "sysdig_reports/archive" # Where the .csv.gz reports are moved after processing - This should be a PVC
            - name: REPORT_SCHEDULE_ID
              value: "2H3Sl0FjEkIocMkVAIfq6CFRSD6" # Report Schedule ID comes from Sysdig UI, click your "All Vulnerabilities" report and grab the Schedule ID from the URL bar
            - name: SYSDIG_SECURE_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: sysdig-secure-api-token
                  key: SYSDIG_SECURE_API_TOKEN
            - name: SYSDIG_REGION_URL
              value: "https://app.au1.sysdig.com" # Your Sysdig Region URL
            - name: ALL_VULNS_TABLE_NAME
              value: "sysdig_vulns" # Name of the table to use in clickhouse to store the vulnerability data (You shouldn't need to change this)
            - name: CLICKHOUSE_HOSTNAME
              value: "clickhouse" # Only need to change if you change the cluster IP svc name
            - name: CLICKHOUSE_USER
              value: "sysdig_vm_user" # Username for Clickhouse DB (You shouldn't need to change this)
            - name: CLICKHOUSE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: clickhouse-password
                  key: CLICKHOUSE_PASSWORD
            #args: ['0']
          restartPolicy: OnFailure