{
 "title": "Vuln Dashboard 1.0 release",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "WorkloadType",
    "query": "select distinct(k8s_workload_type) from ${Table}"
   },
   {
    "name": "Severity",
    "query": "select distinct severity from ${Table}"
   },
   {
    "name": "From",
    "query": "select distinct toString(vuln_first_seen) from ${Table} order by vuln_first_seen DESC"
   },
   {
    "name": "To",
    "query": "select distinct toString(vuln_first_seen) from ${Table} order by vuln_first_seen DESC"
   },
   { "name": "Table", "query": "${VAR_TABLE}" },
   { "name": "Namespace", "label": "Namespace Contains" },
   {
    "name": "PackageType",
    "query": "select distinct package_type from ${Table}"
   },
   {
    "name": "ExcludeNamespaces",
    "query": "select distinct k8s_namespace_name from ${Table}"
   },
   { "name": "InUse", "query": "TRUE,FALSE" },
   { "name": "RiskAccepted", "query": "TRUE,FALSE" },
   { "name": "PublicExploit", "query": "TRUE,FALSE" },
   {
    "name": "Cluster",
    "query": "select DISTINCT(k8s_cluster_name) from ${Table}"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Vulns Open Vulns by Date (Package Type Filter does not apply)",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\n    NULLIF(SUM(CASE WHEN severity = 'Critical' AND k8s_workload_type IN (${WorkloadType}) AND k8s_cluster_name IN (${Cluster}) AND k8s_namespace_name LIKE '%${Namespace}%' and k8s_namespace_name not in (${ExcludeNamespaces}) AND in_use IN (${InUse}) AND risk_accepted IN (${RiskAccepted}) AND public_exploit IN (${PublicExploit}) AND report_date >= '${From}' AND report_date <= '${To}' THEN vuln_count ELSE 0 END), 0) AS \"Critical Vulns\",\n    NULLIF(SUM(CASE WHEN severity = 'High' AND k8s_workload_type IN (${WorkloadType}) AND k8s_cluster_name IN (${Cluster}) AND k8s_namespace_name LIKE '%${Namespace}%' and k8s_namespace_name not in (${ExcludeNamespaces}) AND in_use IN (${InUse}) AND risk_accepted IN (${RiskAccepted}) AND public_exploit IN (${PublicExploit}) AND report_date >= '${From}' AND report_date <= '${To}' THEN vuln_count ELSE 0 END), 0) AS \"High Vulns\",\n    CAST(report_date AS TIMESTAMP) AS Date\nFROM\n    ${Table}_summary\nWHERE severity IN (${Severity}) AND report_date >= '${From}' AND report_date <= '${To}'\nGROUP BY report_date;"
    }
   ]
  },
  {
   "title": "New Vulns Discovered by Date (Package Type Filter does not apply)",
   "type": "barchart",
   "description": "Note: If vulns have been seen before and are re-seen/reopened then this count won't show as a new vuln even though in the above you may seen total count of open vulns has gone up",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\n    COUNT(CASE WHEN severity='Critical' and k8s_workload_type  in (${WorkloadType}) AND k8s_cluster_name IN (${Cluster}) and k8s_namespace_name like '%${Namespace}%' and k8s_namespace_name not in (${ExcludeNamespaces}) AND in_use IN (${InUse}) AND risk_accepted IN (${RiskAccepted}) AND public_exploit IN (${PublicExploit})  and vuln_first_seen >= '${From}' and vuln_first_seen <= '${To}' THEN 1 END) AS \"Critical Vulns\",  -- Counts rows where some_condition is true\n    COUNT(CASE WHEN severity='High' and k8s_workload_type  in (${WorkloadType}) AND k8s_cluster_name IN (${Cluster}) and k8s_namespace_name like '%${Namespace}%' and k8s_namespace_name not in (${ExcludeNamespaces}) AND in_use IN (${InUse}) AND risk_accepted IN (${RiskAccepted}) AND public_exploit IN (${PublicExploit})  and vuln_first_seen >= '${From}' and vuln_first_seen <= '${To}' THEN 1 END) AS \"High Vulns\", -- Counts rows where another_condition is true\n    --COUNT(*) AS TotalCount,  -- Counts all rows in the group\n    CAST(vuln_first_seen AS TIMESTAMP) AS Date\nFROM ${Table}\nWHERE severity in (${Severity}) and vuln_first_seen >= '${From}' and vuln_first_seen <= '${To}'  -- Your overall filtering conditions\nGROUP BY Date;\n"
    }
   ]
  },
  {
   "title": "# of CVE First Seen by Namespace ",
   "type": "table",
   "gridPos": { "h": 17, "w": 18, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT count(*) as \"# Vulns\", vulnerability_id as CVE, severity as Severity, k8s_namespace_name as Namespace, formatDateTime(toDate(vuln_first_seen), '%d %b %y') AS \"First Seen\", vuln_status as \"Vuln Status\"\nFROM ${Table}\nWHERE severity IN (${Severity}) AND k8s_workload_type IN (${WorkloadType}) AND k8s_cluster_name IN (${Cluster}) AND k8s_namespace_name LIKE '%${Namespace}%' and k8s_namespace_name not in (${ExcludeNamespaces}) AND in_use IN (${InUse}) AND risk_accepted IN (${RiskAccepted}) AND public_exploit IN (${PublicExploit})  and vuln_first_seen >= '${From}' and vuln_first_seen <= '${To}'\nGROUP BY vulnerability_id,severity,k8s_namespace_name, vuln_first_seen, vuln_status\nORDER BY \"# Vulns\" DESC"
    }
   ]
  },
  {
   "title": "New Vulns Discovered & Total Vulns Fixed in Date Range",
   "type": "stat",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) as \"# New Vulns Discovered\" from ${Table} where severity in (${Severity}) and k8s_workload_type  in (${WorkloadType}) AND k8s_cluster_name IN (${Cluster}) and package_type in (${PackageType})  and k8s_namespace_name like '%${Namespace}%' and k8s_namespace_name not in (${ExcludeNamespaces}) AND in_use IN (${InUse}) AND risk_accepted IN (${RiskAccepted}) AND public_exploit IN (${PublicExploit})  and vuln_first_seen >= '${From}' and vuln_first_seen <= '${To}'\n"
    },
    {
     "rawSql": "select count(*) as \"# Vulns Resolved\" from ${Table} where severity in (${Severity}) and k8s_workload_type in (${WorkloadType}) AND k8s_cluster_name IN (${Cluster}) and k8s_namespace_name like '%${Namespace}%' and k8s_namespace_name not in (${ExcludeNamespaces}) AND in_use IN (${InUse}) AND risk_accepted IN (${RiskAccepted}) AND public_exploit IN (${PublicExploit})  and vuln_last_seen >= '${From}' and vuln_last_seen <= '${To}' and vuln_status='closed' \n"
    }
   ]
  },
  {
   "title": "Current Vulns & Closed Vulns per Namespace",
   "type": "table",
   "gridPos": { "h": 19, "w": 18, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\n\tk8s_namespace_name as Namespace,\n    COUNT(CASE WHEN vuln_status='open' and k8s_workload_type  in (${WorkloadType}) AND k8s_cluster_name IN (${Cluster}) and k8s_namespace_name like '%${Namespace}%' and k8s_namespace_name not in (${ExcludeNamespaces}) AND in_use IN (${InUse}) AND risk_accepted IN (${RiskAccepted}) AND public_exploit IN (${PublicExploit})  THEN 1 END) AS \"Currently Open Vulns\",\n    COUNT(CASE WHEN vuln_status='closed' and k8s_workload_type  in (${WorkloadType}) AND k8s_cluster_name IN (${Cluster}) and k8s_namespace_name like '%${Namespace}%' and k8s_namespace_name not in (${ExcludeNamespaces}) AND in_use IN (${InUse}) AND risk_accepted IN (${RiskAccepted}) AND public_exploit IN (${PublicExploit})  and vuln_last_seen >= '${From}' and vuln_last_seen <= '${To}' THEN 1 END) AS \"Closed Vulns in Timeframe\"\nFROM ${Table}\nWHERE severity in (${Severity}) and k8s_namespace_name like '%${Namespace}%' and k8s_namespace_name not in (${ExcludeNamespaces})  --and vuln_first_seen >= '${From}' and vuln_first_seen <= '${To}' \nGROUP BY k8s_namespace_name\nORDER by \"Currently Open Vulns\" DESC"
    }
   ]
  },
  {
   "title": "Current Vulns & Closed Vulns per Workload",
   "type": "table",
   "gridPos": { "h": 19, "w": 18, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\n\tk8s_namespace_name as Namespace, k8s_workload_name as Workload,\n    COUNT(CASE WHEN vuln_status='open' and k8s_workload_type  in (${WorkloadType}) AND k8s_cluster_name IN (${Cluster}) and k8s_namespace_name like '%${Namespace}%' and k8s_namespace_name not in (${ExcludeNamespaces}) AND in_use IN (${InUse}) AND risk_accepted IN (${RiskAccepted}) AND public_exploit IN (${PublicExploit})  THEN 1 END) AS \"Currently Open Vulns\",\n    COUNT(CASE WHEN vuln_status='closed' and k8s_workload_type  in (${WorkloadType}) AND k8s_cluster_name IN (${Cluster}) and k8s_namespace_name like '%${Namespace}%' and k8s_namespace_name not in (${ExcludeNamespaces}) AND in_use IN (${InUse}) AND risk_accepted IN (${RiskAccepted}) AND public_exploit IN (${PublicExploit})  and vuln_last_seen >= '${From}' and vuln_last_seen <= '${To}' THEN 1 END) AS \"Closed Vulns in Timeframe\"\nFROM ${Table}\nWHERE severity in (${Severity}) and k8s_namespace_name like '%${Namespace}%' and k8s_namespace_name not in (${ExcludeNamespaces})  --and vuln_first_seen >= '${From}' and vuln_first_seen <= '${To}' \nGROUP BY k8s_namespace_name, k8s_workload_name\nORDER by \"Currently Open Vulns\" DESC"
    }
   ]
  }
 ]
}